include:
  - project: 'kenguru/ci'
    file: '/templates/.gitlab-ci-template.yml'

variables:
  PACKAGE_NAME: backups #Название HELM пакета
  MAIN_PRODUCTION_HOST: backups.kengurutpaps.ru #Основной домен 12
  NAMESPACE_PRODUCTION: backups #NS прод для деплоя в k8s

build:
  script:
    - echo "Building main container"
    - >-
      /kaniko/executor
      --context dir://$CI_PROJECT_DIR/
      --context dir://$CI_PROJECT_DIR/
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination $CI_REGISTRY_IMAGE:$BUILD_TAG
    - echo "Building watcher container"


auto_deploy_staging:
  script:
    - echo "Deploying to staging nope..."
